linters-settings:
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  lll:
    line-length: 100

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gosec
    - gocritic

run:
  timeout: 5m

issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - errcheck
        - gosec