package features

import (
	"fmt"
	"sort"
	"strings"
)

// featureInstallDir is the directory inside the container where feature files
// are copied before their install scripts run.
const featureInstallDir = "/tmp/devgo-features"

// GenerateWrapperDockerfile builds a Dockerfile that layers the given features
// on top of baseImage. For each feature, it COPYs the extracted feature
// directory, emits the feature's containerEnv and resolved option values as ENV
// instructions, and runs install.sh as root.
//
// contextSubdir is the path (relative to the Docker build context) that contains
// the per-feature directories. optionValues maps a feature reference (OCIRef.Raw)
// to its resolved option environment variables.
func GenerateWrapperDockerfile(
	baseImage string,
	feats []*PulledFeature,
	contextSubdir string,
	optionValues map[string]map[string]string,
) string {
	var b strings.Builder

	b.WriteString("# generated by devgo - do not edit\n")
	b.WriteString(fmt.Sprintf("FROM %s\n", baseImage))
	b.WriteString("USER root\n")

	for _, f := range feats {
		id := f.Ref.SanitizedID()
		b.WriteString(fmt.Sprintf("\n# ---- feature: %s ----\n", f.Ref.Raw))
		b.WriteString(fmt.Sprintf("COPY %s/%s %s/%s\n",
			contextSubdir, id, featureInstallDir, id))

		// Feature containerEnv (also persists into the final image).
		for _, line := range envLines(f.Metadata.ContainerEnv) {
			b.WriteString(line)
		}

		// Resolved option values for this feature's install.sh.
		for _, line := range envLines(optionValues[f.Ref.Raw]) {
			b.WriteString(line)
		}

		b.WriteString(fmt.Sprintf("RUN cd %s/%s && chmod +x install.sh && ./install.sh\n",
			featureInstallDir, id))
	}

	if len(feats) > 0 {
		b.WriteString(fmt.Sprintf("\nRUN rm -rf %s\n", featureInstallDir))
	}

	return b.String()
}

// envLines renders a set of environment variables as deterministically ordered
// ENV instructions, one variable per line.
func envLines(env map[string]string) []string {
	if len(env) == 0 {
		return nil
	}
	keys := make([]string, 0, len(env))
	for k := range env {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	lines := make([]string, 0, len(keys))
	for _, k := range keys {
		lines = append(lines, fmt.Sprintf("ENV %s=%s\n", k, quoteEnvValue(env[k])))
	}
	return lines
}

// quoteEnvValue wraps a value in double quotes when it contains whitespace or is
// empty, so the ENV instruction parses as a single value.
func quoteEnvValue(v string) string {
	if v == "" || strings.ContainsAny(v, " \t\"") {
		escaped := strings.ReplaceAll(v, `\`, `\\`)
		escaped = strings.ReplaceAll(escaped, `"`, `\"`)
		return `"` + escaped + `"`
	}
	return v
}
